[tool.poetry]
name = "numbergame"
version = "0.1.0"
description = ""
authors = ["a <silkenpy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.6"
falcon = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
